Deprecate `pown` in favor of `powi`
unageek/inari pull request #70
Opened 2022-02-07 15:12 UTC by Chris00

PR requested at https://github.com/unageek/inari/issues/68

2022-02-07 16:32 UTC, unageek requested changes
Thank you for the PR! Please check the comments.

2022-02-07 17:18 UTC, Chris00 commented on src/elementary.rs
> +    #[deprecated(since="0.13.0", note="Use `powi` instead")]
OK

2022-02-07 17:18 UTC, Chris00 commented on tests/itf1788_tests/libieeep1788_elem.rs
> +fn minimal_powi_dec_test() {
Done.

2022-02-07 17:23 UTC, Chris00 commented
Rebased on /main/.

2022-02-07 23:19 UTC, unageek requested changes
Thanks for the changes!

Could you address https://github.com/unageek/inari/pull/70#issuecomment-1031664050?

2022-02-08 09:45 UTC, unageek approved these changes

2022-02-08 09:57 UTC, merged

2022-02-08 09:57 UTC, unageek commented
Thank you so much!